open_translator.build.variant=${translator.build.variant}
open_translator.version=${project.version}
open_translator.git.branch=${translator.git.branch}
open_translator.git.remote_branch=${translator.git.remoteBranch}
open_translator.git.commit=${translator.git.commit}
